version: "1.4"
namespace:
  key: default
  name: Default
  description: Default namespace
---
namespace:
  key: backend
  name: backend
---
namespace:
  key: staging
  name: staging
---
namespace:
  key: sandbox
  name: sandbox
